# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Short Videos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for Tiktok-Clone-Swift
  pod 'SnapKit'
  pod 'RxSwift', '~> 5'
  pod 'MarqueeLabel'
  pod 'lottie-ios'
  #pod 'BanubaVideoEditorSDK'
  
  # Database
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
  
end
